server.port: 8085
spring:
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/checkinList?serverTimezone=UTC
    username: checkinList
    password: checkinList